# Generated by Django 2.1.4 on 2019-01-03 04:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Browsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('browser', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rating', models.IntegerField(default=0)),
                ('comment', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='screenshots')),
            ],
        ),
        migrations.CreateModel(
            name='Themes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('rating', models.IntegerField()),
                ('price', models.FloatField()),
                ('discount', models.FloatField(blank=True)),
                ('thumbnail', models.ImageField(upload_to='thumbnails')),
                ('version', models.FloatField()),
                ('theme_type', models.CharField(max_length=100)),
                ('bootstrap', models.CharField(max_length=100)),
                ('layouts', models.CharField(max_length=50)),
                ('uses_less', models.BooleanField()),
                ('uses_sass', models.BooleanField()),
                ('labels', models.CharField(max_length=100)),
                ('released', models.CharField(max_length=100)),
                ('browsers', models.ManyToManyField(blank=True, to='themes.Browsers')),
                ('category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='themes.Category')),
                ('owners', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('review', models.ManyToManyField(to='themes.Review')),
                ('screenshot', models.ManyToManyField(blank=True, to='themes.Screenshot')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='themes',
            name='topic',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='themes.Topic'),
        ),
    ]
