# Generated by Django 2.1.4 on 2019-01-04 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='themes',
            name='review',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
