# Generated by Django 2.1.4 on 2019-01-07 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import themes.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('themes', '0004_auto_20190104_0357'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('rating', models.IntegerField()),
                ('price', models.FloatField()),
                ('discount', models.FloatField(blank=True)),
                ('thumbnail', models.ImageField(upload_to=themes.models.thumbnail_upload_path)),
                ('version', models.FloatField()),
                ('theme_type', models.CharField(max_length=100)),
                ('bootstrap', models.CharField(max_length=100)),
                ('layouts', models.CharField(max_length=50)),
                ('uses_less', models.BooleanField()),
                ('uses_sass', models.BooleanField()),
                ('labels', models.CharField(max_length=100)),
                ('released', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='themes',
            name='browsers',
        ),
        migrations.RemoveField(
            model_name='themes',
            name='category',
        ),
        migrations.RemoveField(
            model_name='themes',
            name='owners',
        ),
        migrations.RemoveField(
            model_name='themes',
            name='review',
        ),
        migrations.RemoveField(
            model_name='themes',
            name='screenshot',
        ),
        migrations.RemoveField(
            model_name='themes',
            name='topic',
        ),
        migrations.AlterField(
            model_name='screenshot',
            name='image',
            field=models.ImageField(upload_to=themes.models.screenshot_upload_path),
        ),
        migrations.RenameModel(
            old_name='Browsers',
            new_name='Browser',
        ),
        migrations.DeleteModel(
            name='Themes',
        ),
        migrations.AddField(
            model_name='theme',
            name='browser',
            field=models.ManyToManyField(blank=True, to='themes.Browser'),
        ),
        migrations.AddField(
            model_name='theme',
            name='category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='themes.Category'),
        ),
        migrations.AddField(
            model_name='theme',
            name='owners',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='theme',
            name='review',
            field=models.ManyToManyField(blank=True, to='themes.Review'),
        ),
        migrations.AddField(
            model_name='theme',
            name='screenshot',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='themes.Screenshot'),
        ),
        migrations.AddField(
            model_name='theme',
            name='topic',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='themes.Topic'),
        ),
    ]
