# Generated by Django 2.1.4 on 2019-01-07 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0005_auto_20190107_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='screenshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='themes.Screenshot'),
        ),
    ]
