# Generated by Django 2.1.4 on 2019-01-07 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0007_auto_20190107_0849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='thumbnail',
        ),
        migrations.DeleteModel(
            name='Thumbnail',
        ),
    ]
