# Generated by Django 2.1.4 on 2019-01-07 08:53

from django.db import migrations, models
import django.db.models.deletion
import themes.models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0008_auto_20190107_0853'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thumbnail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(upload_to=themes.models.thumbnail_upload_path)),
            ],
        ),
        migrations.AddField(
            model_name='theme',
            name='thumbnail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='themes.Thumbnail'),
        ),
    ]
