# Generated by Django 2.1.4 on 2019-01-07 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0009_auto_20190107_0853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='screenshot',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='thumbnail',
        ),
        migrations.DeleteModel(
            name='Screenshot',
        ),
        migrations.DeleteModel(
            name='Thumbnail',
        ),
    ]
