# Generated by Django 2.1.4 on 2019-01-07 08:59

from django.db import migrations, models
import django.db.models.deletion
import themes.models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0010_auto_20190107_0859'),
    ]

    operations = [
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=themes.models.screenshot_upload_path)),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='themes.Theme')),
            ],
        ),
        migrations.CreateModel(
            name='Thumbnail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(upload_to=themes.models.thumbnail_upload_path)),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='themes.Theme')),
            ],
        ),
    ]
