# Generated by Django 2.1.4 on 2019-01-08 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0011_screenshot_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.RemoveField(
            model_name='screenshot',
            name='theme',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='browser',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='category',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='owners',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='review',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='thumbnail',
            name='theme',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='Screenshot',
        ),
        migrations.DeleteModel(
            name='Theme',
        ),
        migrations.DeleteModel(
            name='Thumbnail',
        ),
    ]
