# Generated by Django 2.1.4 on 2019-01-08 02:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import themes.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('themes', '0012_auto_20190108_0240'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
                ('comment', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=themes.models.screenshot_upload_path)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('rating', models.IntegerField(blank=True)),
                ('price', models.FloatField()),
                ('discount', models.FloatField(blank=True)),
                ('version', models.CharField(blank=True, max_length=50)),
                ('theme_type', models.CharField(max_length=100)),
                ('bootstrap', models.CharField(max_length=100)),
                ('layouts', models.CharField(max_length=50)),
                ('uses_less', models.BooleanField()),
                ('uses_sass', models.BooleanField()),
                ('labels', models.CharField(max_length=100)),
                ('released', models.DateField(blank=True)),
                ('browser', models.ManyToManyField(blank=True, to='themes.Browser')),
                ('category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='themes.Category')),
                ('owners', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='themes.Topic')),
            ],
        ),
        migrations.CreateModel(
            name='Thumbnail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(upload_to=themes.models.thumbnail_upload_path)),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='themes.Theme')),
            ],
        ),
        migrations.AddField(
            model_name='screenshot',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='themes.Theme'),
        ),
        migrations.AddField(
            model_name='review',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='themes.Theme'),
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
