# Generated by Django 2.1.4 on 2019-01-08 02:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0013_auto_20190108_0240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='rating',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(5)]),
        ),
    ]
