# Generated by Django 2.1.4 on 2019-01-08 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0015_auto_20190108_0251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='theme',
            old_name='released',
            new_name='release_date',
        ),
    ]
