# Generated by Django 2.1.4 on 2019-01-08 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0016_auto_20190108_0252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='discount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
