# Generated by Django 2.1.5 on 2019-01-31 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0019_auto_20190108_0553'),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license', models.CharField(max_length=100)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_modified', models.DateField(auto_now=True)),
            ],
        ),
    ]
