# Generated by Django 2.1.5 on 2019-01-31 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0020_license'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='license',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='themes.License'),
        ),
    ]
