# Generated by Django 2.1.5 on 2019-02-17 07:11

from django.db import migrations, models
import themes.models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0022_auto_20190212_0818'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='downloads',
            field=models.IntegerField(default=0),
        ),
    ]
